export const productsMenu = [
  { id: 1, name: 'aventais' },
  { id: 2, name: 'bolsas' },
  { id: 3, name: 'carteiras' },
  { id: 4, name: 'diversos' },
  { id: 5, name: 'ecobags' },
  { id: 6, name: 'estojos' },
  { id: 7, name: 'higiene' },
  { id: 8, name: 'infantil' },
  { id: 9, name: 'kits de cozinha' },
  { id: 10, name: 'lancheiras' },
  { id: 11, name: 'necessaires' },
  { id: 12, name: 'panos de prato' },
  { id: 13, name: 'porta óculos' },
  { id: 14, name: 'puxa sacos' },
  { id: 15, name: 'toalhas' },
  { id: 16, name: 'toucas' },
];
